services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      APP_ENV: production
      APP_KEY: ${APP_KEY}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - storage_data:/var/www/html/storage/app
    networks:
      - mosso_net

  db:
    image: mariadb:10.4
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mosso_net

volumes:
  db_data:
  storage_data:

networks:
  mosso_net:
    driver: bridge
